name: Run Tests

on:
  push:
  pull_request:

jobs:
  test:
    runs-on: ubuntu-latest


    steps:
    - uses: actions/checkout@v2
    - name: Use Node.js 16
      uses: actions/setup-node@v2
      with:
        node-version: 16
    - run: npm ci
      working-directory: trump-game
    - run: npm run build
      working-directory: trump-game
    - run: npm test
      working-directory: trump-game
